#
# docker-compose build --force-rm [--no-cache [<SERVICE_NAME>...]]
# docker-compose up -d --remove-orphans
# docker-compose logs -f [--tail=1 <SERVICE_NAME>...]
# docker-compose down -v --remove-orphans
#
version: '2'
services:
  tomcat:
    build: ./tomcat
    ports:
      - '1337:1337' # container (http)
      - '8080:8080' # tomcat (http)
      - '9443:9443' # bps (https)
      - '9763:9763' # bps (http)
      # - '9975:2375' # dind (tcp)
      - '8888:80' # dind
      - '9990-9999:9990-9999' # dind
    volumes:
      - '/usr/local/tomcat/webapps'
    environment:
      - TOMCAT_USERNAME=tcManager
      - TOMCAT_PASSWORD=4Syq5MQeedIDzzP6BG7b
  opentosca-container:
    build:
      context: ./opentosca-container
      args:
        - GIT_BRANCH=master
    network_mode: 'service:tomcat'
  bps:
    build: ./bps
    network_mode: 'service:tomcat'
  dind:
    image: jpetazzo/dind:latest
    privileged: true
    network_mode: 'service:tomcat'
    environment:
      - PORT=2375
      # - DOCKER_DAEMON_ARGS=--dns 8.8.8.8 --dns 8.8.4.4 -D
      # Internal DNS settings to run it inside the univeristy network
      - DOCKER_DAEMON_ARGS=--dns 129.69.211.1 --dns 129.69.215.5 -D
    volumes:
      - ./demo:/opt
  opentosca-ui:
    build:
      context: ./opentosca-ui
      args:
        - GIT_BRANCH=master
    ports:
      - '8088:8088'
  winery:
    build:
      context: ./winery
      args:
        - GIT_BRANCH=master
    volumes_from:
      - tomcat
    depends_on:
      - tomcat
  winery-bpmn4tosca:
    build:
      context: ./winery-bpmn4tosca
      args:
        - GIT_BRANCH=master
    volumes_from:
      - tomcat
    depends_on:
      - winery
